<?php
/**
 * @version         1.0.3
 * @package         components
 * @sub package     com_jeproshop
 * @link            http://jeprodev.net/index.php?option=com_jeproshop&view=product&product_id=1
 *
 * @copyright (C)   2009 - 2011
 * @license         http://www.gnu.org/copyleft/gpl.html GNU/GPL
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of,
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');

class JeproshopShopController extends JeproshopController{
    /*public function initContent(){
        if(!$this->viewAccess()){
            JError::raiseWarning(500, JText::_('COM_JEPROSHOP_YOU_DO_NOT_HAVE_PERMISSION_TO_VIEW_THIS_PAGE_MESSAGE'));
        }

        $this->getLanguages();
        $app = JFactory::getApplication();

        $task = $app->input->get('task');
        $view = $app->input->get('view');
        $viewClass = $this->getView($view, JFactory::getDocument()->getType());

        if($task == 'edit' || $task == 'add') {
            if (!$viewClass->loadObject(true)) {
                return false;
            }
            $viewClass->setLayout('edit');
            $viewClass->renderEditForm();
        }
        
        return parent::initContent(); // TODO: Change the autogenerated stub
    }*/

    public function update(){
        $app = JFactory::getApplication();
        $tab = $app->input->get('tab');
        $useAjax = $app->input->get('use_ajax');
        $jsonData = array("success" => false, "found" => false);

        if($this->viewAccess()) {
            switch ($tab) {
                case 'group' :
                    if($this->canEdit('shop_group')) {
                        $shopGroupId = $app->input->get('shop_group_id');
                        $shopGroup = new JeproshopShopGroupModelShopGroup($shopGroupId);

                        if (!JeproshopTools::isLoadedObject($shopGroup, 'shop_group_id')) {
                            if ($useAjax) {

                            }
                        } else {
                            if ($shopGroup->update()) {
                                echo ' gjhdgjf';
                            }
                        }
                    }
                break;
            }
        }

        if($useAjax){
            $document = JFactory::getDocument();
            $document->setMimeEncoding('application/json');
            echo json_encode($jsonData);
            $app->close();
        }
    }

    public function delete(){
        $app = JFactory::getApplication();
        $tab = $app->input->get('tab');
        $useAjax = $app->input->get('use_ajax');
        $jsonData = array("success" => false, "found" => false);

        if($this->viewAccess()){
            switch($tab){
                case 'group' :
                    if($this->canEdit('shop_group')) {
                        $shopGroupId = $app->input->get('shop_group_id', 0);
                        $shopGroup = new JeproshopShopGroupModelShopGroup($shopGroupId);
                        if(!JeproshopTools::isLoadedObject($shopGroup, 'shop_group_id')){
                            $message = JText::_('COM_JEPROSHOP_SHOP_GROUP_NOT_FOUND_MESSAGE');
                        }else{
                            if(JeproshopShopGroupModelShopGroup::getTotalShopGroup() == 1){
                                $message = JText::_('COM_JEPROSHOP_YOU_CANNOT_DELETE_OR_DISABLE_THE_LAST_SHOP_GROUP_MESSAGE');
                            }else if($shopGroup->haveShopd()){
                                $message = JText::_('COM_JEPROSHOP_YOU_CANNOT_DELETE_OR_DISABLE_THE_SHOP_GROUP_IN_USE_MESSAGE');
                            }

                            if($shopGroup->delete()){
                                $message = JText::_('COM_JEPROSHOP_THE_SHOP_GROUP_HAS_BEEN_SUCCESSFULLY_DELETED_MESSAGE');
                            }
                        }
                    }else{ $message = JText::_('COM_JEPROSHOP_YOU_HAVE_NO_RIGHT_DELETING_SHOP_GROUP_DATA_MESSAGE'); }
            }
        }

        if($useAjax){
            $document = JFactory::getDocument();
            $document->setMimeEncoding('application/json');
            echo json_encode($jsonData);
            $app->close();
        }
    }
}